"""
Trade Tracker API - Entry point.

Start locally:
    uvicorn main:app --reload --port 8000

In Docker:
    CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs    <- Swagger UI
    http://localhost:8000/redoc  <- ReDoc
"""
import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

import config
import db
from routers import ibkr, imports, market, portfolio, trades

logging.basicConfig(
    level=logging.DEBUG if config.DEBUG else logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="DeKalb Trade Tracker API",
    description=(
        "Backend API for the DeKalb hedge fund trade tracker. "
        "Tracks trades from IBKR and Fidelity, calculates portfolio metrics "
        "(beta, std dev, NAV), and serves data to the frontend dashboard."
    ),
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Allow the frontend (React dev server on :3000 and production on :80)
# NOTE: allow_credentials=True requires explicit origins (not "*")
_allowed_origins = [
    "http://localhost:3000",
    "http://localhost:80",
    "http://localhost",
]
# Add production frontend URL if configured (e.g. https://dekalb-tracker.vercel.app)
if config.FRONTEND_URL and config.FRONTEND_URL not in _allowed_origins:
    _allowed_origins.append(config.FRONTEND_URL)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(portfolio.router)
app.include_router(trades.router)
app.include_router(imports.router)
app.include_router(market.router)
app.include_router(ibkr.router)


@app.on_event("startup")
async def startup():
    await db.init_pool()
    logger.info("Trade Tracker API started. Docs at /docs")

    if config.IBKR_ENABLED:
        # Connect to IBKR using RSA key credentials (server-to-server, no user action needed).
        # Runs in a background thread so the API starts immediately regardless.
        import threading
        from services.ibkr_client import ibkr_client
        t = threading.Thread(target=ibkr_client.connect, daemon=True)
        t.start()
        logger.info("IBKR connection starting in background (client_id=%s)", config.IBKR_CLIENT_ID)
    else:
        logger.info("IBKR DISABLED — using yfinance for market data. Set IBKR_ENABLED=true to activate.")


@app.on_event("shutdown")
async def shutdown():
    if config.IBKR_ENABLED:
        from services.ibkr_client import ibkr_client
        ibkr_client.disconnect()
    await db.close_pool()
    logger.info("Trade Tracker API stopped")


@app.get("/health", tags=["health"])
async def health():
    """Health check endpoint."""
    pool = db.get_pool()
    try:
        await pool.fetchval("SELECT 1")
        db_ok = True
    except Exception:
        db_ok = False

    return {
        "status": "ok" if db_ok else "degraded",
        "database": "connected" if db_ok else "unreachable",
        "ibkr": "enabled (Web API)" if config.IBKR_ENABLED else "disabled (yfinance fallback)",
        "version": "0.1.0",
    }
