"""
Trade Tracker API - Entry point.

Start locally:
    uvicorn main:app --reload --port 8000

In Docker:
    CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs    <- Swagger UI
    http://localhost:8000/redoc  <- ReDoc
"""
import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

import config
import db
from routers import ibkr, imports, market, portfolio, trades

logging.basicConfig(
    level=logging.DEBUG if config.DEBUG else logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="DeKalb Trade Tracker API",
    description=(
        "Backend API for the DeKalb hedge fund trade tracker. "
        "Tracks trades from IBKR and Fidelity, calculates portfolio metrics "
        "(beta, std dev, NAV), and serves data to the frontend dashboard."
    ),
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Allow frontend dev server (UX team uses separate origin)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten this to specific origins in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(portfolio.router)
app.include_router(trades.router)
app.include_router(imports.router)
app.include_router(market.router)
app.include_router(ibkr.router)


@app.on_event("startup")
async def startup():
    await db.init_pool()
    logger.info("Trade Tracker API started. Docs at /docs")
    if config.IBKR_ENABLED:
        logger.info("IBKR ENABLED via Pangolin at %s (account: %s)", config.IBKR_PANGOLIN_URL, config.IBKR_ACCOUNT_ID)
    else:
        logger.info("IBKR DISABLED — using yfinance for market data. Set IBKR_ENABLED=true to activate.")


@app.on_event("shutdown")
async def shutdown():
    await db.close_pool()
    logger.info("Trade Tracker API stopped")


@app.get("/health", tags=["health"])
async def health():
    """Health check endpoint."""
    pool = db.get_pool()
    try:
        await pool.fetchval("SELECT 1")
        db_ok = True
    except Exception:
        db_ok = False

    return {
        "status": "ok" if db_ok else "degraded",
        "database": "connected" if db_ok else "unreachable",
        "ibkr": "enabled" if config.IBKR_ENABLED else "disabled (yfinance fallback)",
        "version": "0.1.0",
    }
